version: '3.9'

services:
  aesm:
    image: initc3/linux-sgx:2.13-ubuntu20.04
    devices:
      - /dev/isgx
    volumes:
      - aesmd-socket:/var/run/aesmd
      #- ./aesmd.conf:/etc/aesmd.conf
    user: aesmd
    #stdin_open: true
    #tty: true
    working_dir: /opt/intel/sgx-aesm-service/aesm
    environment:
      LD_LIBRARY_PATH: /opt/intel/sgx-aesm-service/aesm
    command: ./aesm_service --no-daemon

  sgxiot:
    image: sgx_iot
    build:
      context: .
      dockerfile: Dockerfile
      #args:
      #  SGX_MODE: hw
      #  SGX_DEBUG: 0
    depends_on:
      - aesm
    devices:
      - /dev/isgx
    environment:
      SGX_SPID: ${SGX_SPID}
      IAS_PRIMARY_KEY: ${IAS_PRIMARY_KEY}
      PYTHONBREAKPOINT: ipdb.set_trace
    env_file: .env
    volumes:
      - aesmd-socket:/var/run/aesmd
      - ./demo_sgx:/usr/src/sgxiot/demo_sgx
      - ./.enclavehub.yml:/usr/src/sgxiot/.enclavehub.yml
      - ./enclave.nix:/usr/src/sgxiot/enclave.nix
      - ./verify.py:/usr/src/sgxiot/verify.py
      - ./run_keygen.sh:/usr/src/sgxiot/run_keygen.sh
      - ./run_quote.sh:/usr/src/sgxiot/run_quote.sh
      - ./run_demo_sgxra.sh:/usr/src/sgxiot/run_demo_sgxra.sh
      - /var/run/docker.sock:/var/run/docker.sock
    #command: ./run_demo_sgx.sh
    command: ./run_demo_sgxra.sh

volumes:
  aesmd-socket:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
      o: "rw"
